framework:
  secret: '%env(APP_SECRET)%'
  #csrf_protection: true
  http_method_override: false
  handle_all_throwables: true

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native

  #esi: true
  #fragments: true
  php_errors:
    log: true

  cache:
    # Unique name of your app: used to compute stable namespaces for cache keys.
    #prefix_seed: your_vendor_name/app_name

    # The "app" cache stores to the filesystem by default.
    # The data in this cache should persist between deploys.
    # Other options include: cache.adapter.redis, cache.adapter.memcached, cache.adapter.pdo, cache.adapter.system, cache.adapter.filesystem
    app: cache.adapter.filesystem

    # The "system" cache is for Symfony's internal use.
    # If you modify it, the cache pool should at least have these adapters as its base:
    system: cache.adapter.system

  serializer:
    enabled: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file