# API Routes
api:
  resource: ../src/Controller/
  type: attribute
  prefix: /api

nelmio_api_doc_index:
  path: /api/doc
  methods: GET
  defaults:
    _controller: nelmio_api_doc.controller.swagger_ui